#!/bin/sh
# Refreshes local Artificial Analysis snapshots. This is the only AA network client.
set -eu
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
AGENT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
CONFIG=${PI_AA_SETTINGS_CONFIG:-$AGENT_DIR/settings.config.json}; MODELS=${PI_AA_MODELS_CONFIG:-$AGENT_DIR/models.json}; CREDENTIALS=${PI_CREDENTIALS_CONFIG:-$AGENT_DIR/credentials.json}
ROOT=${PI_AA_SNAPSHOT_ROOT:-$AGENT_DIR/extensions/04-subagents/assets/aa}; MANIFEST=$ROOT/manifest.json; MODELS_DIR=$ROOT/models
AA_API_URL=${PI_AA_API_URL:-https://artificialanalysis.ai/api/v2/language/models}; AA_PUBLIC_ORIGIN=https://artificialanalysis.ai; SNAPSHOT_VERSION=4; EXPECTED_INDEX_VERSION=4.1; EXPECTED_PAGE_INDEX_VERSION=4.1.1; METHODOLOGY_ID=artificial-analysis-intelligence-index; MAX_BYTES=${PI_AA_MAX_BYTES:-2097152}; PUBLIC_MAX_BYTES=${PI_AA_PUBLIC_MAX_BYTES:-8388608}; MAX_PAGES=20; MAX_AGE_MS=${PI_AA_SNAPSHOT_MAX_AGE_MS:-2592000000}; PAGE_DELAY=${PI_AA_PUBLIC_PAGE_DELAY:-1}; PAGE_MAX_REDIRECTS=${PI_AA_PUBLIC_PAGE_MAX_REDIRECTS:-2}; EXTRACTOR_VERSION=aa-current-model-rsc-v1
fail() { echo "refresh-artificial-analysis: $*" >&2; exit 1; }
for f in "$CONFIG" "$MODELS"; do [ -r "$f" ] || fail "missing $(basename "$f")"; done
for x in jq curl mktemp cmp chmod mv wc stat awk grep sed; do command -v "$x" >/dev/null 2>&1 || fail "$x is required"; done
case $MAX_BYTES in ''|*[!0-9]*) fail "PI_AA_MAX_BYTES must be a positive integer";; esac
[ "$MAX_BYTES" -gt 0 ] || fail "PI_AA_MAX_BYTES must be a positive integer"
case $PUBLIC_MAX_BYTES in ''|*[!0-9]*) fail "PI_AA_PUBLIC_MAX_BYTES must be a positive integer";; esac
[ "$PUBLIC_MAX_BYTES" -gt 0 ] || fail "PI_AA_PUBLIC_MAX_BYTES must be a positive integer"
case $PAGE_MAX_REDIRECTS in ''|*[!0-9]*) fail "PI_AA_PUBLIC_PAGE_MAX_REDIRECTS must be an integer";; esac
case $PAGE_DELAY in ''|*[!0-9.]*|.*.*) fail "PI_AA_PUBLIC_PAGE_DELAY must be a non-negative decimal";; esac
WORK=$(mktemp -d "${TMPDIR:-/tmp}/pi-aa-refresh.XXXXXX"); cleanup() { rm -rf -- "$WORK"; }; trap cleanup EXIT HUP INT TERM
usage() { cat >&2 <<'EOF'
Usage: refresh-artificial-analysis.sh --missing|--check
       refresh-artificial-analysis.sh --discover provider/model
       refresh-artificial-analysis.sh --add provider/model --aa-model-id ID [--thinking-level LEVEL]
       refresh-artificial-analysis.sh --replace-batch FILE
       refresh-artificial-analysis.sh --refresh provider/model|--refresh-all

Snapshot-producing commands supplement null API evaluation components from the
canonical public model page. They never map uncallable Pi reasoning variants.
EOF
}
hash_stream() { if command -v sha256sum >/dev/null 2>&1; then sha256sum | awk '{print $1}'; elif command -v shasum >/dev/null 2>&1; then shasum -a 256 | awk '{print $1}'; else fail "sha256sum or shasum is required"; fi; }
assert_mode() { if mode=$(stat -f '%Lp' "$1" 2>/dev/null); then :; else mode=$(stat -c '%a' "$1") || fail "cannot inspect mode: $1"; fi; [ "$mode" = "$2" ] || fail "unsafe permissions on $1 (expected $2)"; }
configured_models() { jq -r '.enabledModels[]? | select(type == "string" and test("^[^/]+/.+"))' "$CONFIG" | LC_ALL=C sort -u; }
valid_level() { case ${1-} in null|off|low|medium|high|xhigh|max) return 0;; *) return 1;; esac; }
entry_sort() { jq -j -S -c '.models | sort_by(.provider,.model,(.thinkingLevel // ""))'; }

check_snapshot() {
 [ -f "$MANIFEST" ] || fail "no benchmark manifest; run --add after reviewing --discover output"; [ -d "$ROOT" ] && [ -d "$MODELS_DIR" ] || fail "invalid benchmark snapshot directories"; assert_mode "$ROOT" 700; assert_mode "$MODELS_DIR" 700; assert_mode "$MANIFEST" 600; now=$(date +%s)000
 jq -e --argjson now "$now" --argjson maxAge "$MAX_AGE_MS" --arg id "$METHODOLOGY_ID" --arg version "$EXPECTED_INDEX_VERSION" '
 . as $root | $root.version == 4 and ($root.generatedAt|type == "number") and $root.generatedAt <= $now and $root.generatedAt >= ($now - $maxAge) and ($root.digest|type == "string" and test("^[a-f0-9]{64}$")) and ($root.methodology == {id:$id,version:$version}) and ($root.models|type == "array")
 and ([$root.models[] | select((.provider|type == "string" and length>0) and (.model|type == "string" and length>0) and (.thinkingLevel == null or .thinkingLevel == "off" or .thinkingLevel == "low" or .thinkingLevel == "medium" or .thinkingLevel == "high" or .thinkingLevel == "xhigh" or .thinkingLevel == "max") and (.modelId|type == "string" and length>0) and (.file|type == "string" and test("^[A-Za-z0-9_-]+\\.json$")) and (.capturedAt|type == "number") and (.contentDigest|type == "string" and test("^[a-f0-9]{64}$")))]|length == ($root.models|length))
 and ([$root.models | group_by([.provider,.model,.thinkingLevel])[] | select(length>1)]|length == 0) and ([$root.models | group_by(.file)[] | select(length>1)]|length == 0) and ([$root.models | group_by([.provider,.model,.modelId])[] | select(length>1)]|length == 0) and ([$root.models | group_by([.provider,.model])[] | select(length>1 and any(.[]; .thinkingLevel == null))]|length == 0)' "$MANIFEST" >/dev/null || fail "invalid or unsupported manifest"
 expected=$(jq -r .digest "$MANIFEST"); actual=$(entry_sort < "$MANIFEST" | hash_stream); [ "$expected" = "$actual" ] || fail "manifest digest mismatch"
 jq -r '.models[] | [.provider,.model,(.thinkingLevel // "null"),.modelId,.file,(.capturedAt|tostring),.contentDigest] | @tsv' "$MANIFEST" | while IFS="$(printf '\t')" read -r p m level aa file captured content; do
  [ -r "$MODELS_DIR/$file" ] || fail "manifest references missing snapshot: $file"; assert_mode "$MODELS_DIR/$file" 600; [ "$(jq -j -S -c . "$MODELS_DIR/$file" | hash_stream)" = "$content" ] || fail "snapshot digest mismatch: $file"
  jq -e --arg p "$p" --arg m "$m" --arg level "$level" --arg aa "$aa" --argjson captured "$captured" --argjson now "$now" --argjson maxAge "$MAX_AGE_MS" --arg id "$METHODOLOGY_ID" --arg version "$EXPECTED_INDEX_VERSION" --arg extractor "$EXTRACTOR_VERSION" --arg pageVersion "$EXPECTED_PAGE_INDEX_VERSION" '
   def score: . == null or (type == "number" and . >= 0 and . <= 100);
   def profileMetrics: . as $metrics | type == "object" and ([to_entries[] | select((.key == "balanced" or .key == "coding" or .key == "agentic" or .key == "research" or .key == "planning" or .key == "review" or .key == "long-context") and (.value == null or (.value|type == "number" and . >= 0)))] | length) == ($metrics|length);
   . as $s | def component($id): (keys|sort) == ["benchmark","fieldPath","normalizedScore","retrievedAt","sourceKind","sourceRecordDigest","sourceUrl"] and (.normalizedScore|score) and (.fieldPath|type == "string" and length>0) and (.retrievedAt|type == "number" and . <= $s.capturedAt) and (.sourceRecordDigest|type == "string" and test("^[a-f0-9]{64}$")) and (.benchmark|keys|sort) == ["id","status","version"] and .benchmark.id == $id and (.benchmark.version|type == "string" and length>0) and (.benchmark.status|type == "string" and length>0) and (if .sourceKind == "api" then (.sourceUrl|type == "string" and contains("/api/")) elif .sourceKind == "public-page" then (.sourceUrl == $s.publicPage.url and .sourceRecordDigest == $s.publicPage.recordSha256) else false end);
   ($s|keys|sort) == ["capturedAt","coverage","mapping","methodology","model","modelId","outputTokens","provider","publicPage","scores","source","taskTimeMs","thinkingLevel","toolUse","version"]
   and $s.version == 4 and $s.provider == $p and $s.model == $m and ($s.thinkingLevel == (if $level == "null" then null else $level end)) and $s.modelId == $aa and $s.capturedAt == $captured and $s.capturedAt <= $now and $s.capturedAt >= ($now - $maxAge) and $s.methodology == {id:$id,version:$version}
   and ($s.mapping|keys|sort) == ["matchBasis","reviewedAt","status","thinkingLevel"] and $s.mapping.status == "mapped" and $s.mapping.matchBasis == "manual" and ($s.mapping.reviewedAt|type == "number") and $s.mapping.thinkingLevel == $s.thinkingLevel
   and ($s.source|keys|sort) == ["name","openrouterApiId","slug"] and ($s.source.name|type == "string" and length>0) and ($s.source.slug|type == "string" and test("^[a-z0-9]+(?:-[a-z0-9]+)*$")) and ($s.source.openrouterApiId == null or ($s.source.openrouterApiId|type == "string"))
   and ($s.publicPage|keys|sort) == ["contentSha256","extractorVersion","intelligenceIndexMethodologyVersion","recordSha256","retrievedAt","url"] and $s.publicPage.url == ("https://artificialanalysis.ai/models/" + $s.source.slug) and ($s.publicPage.retrievedAt|type=="number") and $s.publicPage.retrievedAt <= $captured and ($s.publicPage.contentSha256|type=="string" and test("^[a-f0-9]{64}$")) and ($s.publicPage.recordSha256|type=="string" and test("^[a-f0-9]{64}$")) and $s.publicPage.extractorVersion==$extractor and $s.publicPage.intelligenceIndexMethodologyVersion==$pageVersion
   and ($s.scores|keys|sort) == ["agentic","coding","faithfulness","instructionFollowing","intelligence","knowledge","longContext","scientificReasoning","toolUse"] and ([$s.scores[]|select(score|not)]|length == 0)
   and ($s.toolUse|keys|sort) == ["components","derivation"]
   and ($s.toolUse.components|keys|sort) == ["gdpvalAaNormalized","tau2Telecom","tau3Banking"]
   and ($s.toolUse.components.tau3Banking == null or ($s.toolUse.components.tau3Banking|component("tau3-banking")))
   and ($s.toolUse.components.gdpvalAaNormalized == null or ($s.toolUse.components.gdpvalAaNormalized|component("gdpval-aa")))
   and ($s.toolUse.components.tau2Telecom == null or ($s.toolUse.components.tau2Telecom|component("tau2-telecom")))
   and ($s.toolUse.derivation|keys|sort) == ["rule","score","version"] and $s.toolUse.derivation.version == "v1"
   and (if ($s.toolUse.components.tau3Banking != null and $s.toolUse.components.gdpvalAaNormalized != null) then ($s.toolUse.derivation == {version:"v1",rule:"tau3-banking+gdpval-aa",score:(($s.toolUse.components.tau3Banking.normalizedScore + $s.toolUse.components.gdpvalAaNormalized.normalizedScore) / 2)}) elif $s.toolUse.components.tau2Telecom != null then ($s.toolUse.derivation == {version:"v1",rule:"tau2-telecom-fallback",score:$s.toolUse.components.tau2Telecom.normalizedScore}) else ($s.toolUse.derivation == {version:"v1",rule:"unavailable",score:null}) end)
   and $s.scores.toolUse == $s.toolUse.derivation.score and ($s.coverage|type == "number" and .>=0 and .<=1) and (($s.coverage - (([$s.scores[]|select(.!=null)]|length) / 9))|fabs) <= 1e-9 and ($s.outputTokens|profileMetrics) and ($s.taskTimeMs|profileMetrics)' "$MODELS_DIR/$file" >/dev/null || fail "invalid snapshot: $file"
 done
}
missing() { configured_models | while IFS= read -r id; do p=${id%%/*}; m=${id#*/}; if [ ! -f "$MANIFEST" ] || ! jq -e --arg p "$p" --arg m "$m" '.models[]? | select(.provider == $p and .model == $m)' "$MANIFEST" >/dev/null; then printf '%s\n' "$id"; fi; done; }
setup_curl_config() { if [ -z "${AA_API_KEY:-}" ]; then [ -r "$CREDENTIALS" ] || fail "Artificial Analysis API key is missing from agent/credentials.json"; assert_mode "$CREDENTIALS" 600; AA_API_KEY=$(jq -er '.artificialAnalysis.apiKey | select(type == "string" and length > 0)' "$CREDENTIALS" 2>/dev/null) || fail "Artificial Analysis API key is missing from agent/credentials.json"; fi; CURL_CONFIG=$WORK/curl.conf; umask 077; printf 'header = "x-api-key: %s"\n' "$AA_API_KEY" > "$CURL_CONFIG"; chmod 600 "$CURL_CONFIG"; }
api_get() { curl -q --fail --silent --show-error --max-time 30 --connect-timeout 5 --max-filesize "$MAX_BYTES" --config "$CURL_CONFIG" "$1" > "$2" || fail "Artificial Analysis API request failed"; bytes=$(wc -c < "$2" | tr -d ' '); [ "$bytes" -le "$MAX_BYTES" ] || fail "Artificial Analysis response exceeded byte limit"; jq -e . "$2" >/dev/null || fail "Artificial Analysis returned invalid JSON"; }
fetch_catalog() { out=$1; : > "$WORK/catalog.ndjson"; page=1; version=; while :; do [ "$page" -le "$MAX_PAGES" ] || fail "Artificial Analysis pagination exceeded limit"; body=$WORK/page-$page.json; api_get "$AA_API_URL?page=$page&page_size=200" "$body"; jq -e '.data|type == "array"' "$body" >/dev/null || fail "Artificial Analysis response has no model array"; current=$(jq -r '.intelligence_index_version|tostring' "$body"); [ "$current" = "$EXPECTED_INDEX_VERSION" ] || fail "unsupported Artificial Analysis Intelligence Index version: $current"; [ -z "$version" ] || [ "$version" = "$current" ] || fail "Artificial Analysis methodology changed during pagination"; version=$current; jq -c '.data[] | select(type == "object" and (.id|type == "string"))' "$body" >> "$WORK/catalog.ndjson"; [ "$(jq -r '.pagination.has_more // false' "$body")" = true ] || break; page=$((page+1)); done; jq -s --arg version "$version" '{intelligenceIndexVersion:$version,data:.}' "$WORK/catalog.ndjson" > "$out"; }
# Decode only Next Flight/RSC string chunks, then extract brace-balanced currentModel JSON.
# Plain HTML or script decoys are never considered benchmark evidence.
extract_current_models() {
 frames=$WORK/rsc-frames.txt; decoded=$WORK/rsc-decoded.txt; : > "$decoded"
 sed 's#</script>#</script>\
#g' "$1" | sed -n 's#^.*self\.__next_f\.push(\(\[.*\]\))</script>.*$#\1#p' > "$frames"
 [ -s "$frames" ] || return 1
 while IFS= read -r frame; do payload=$(printf '%s' "$frame" | jq -er 'select(type == "array" and length >= 2) | .[1] | select(type == "string")') || return 1; printf '%s\n' "$payload" >> "$decoded"; done < "$frames"
 awk '
function emit_object(start,  i,c,depth,quoted,escaped) { depth=0; quoted=0; escaped=0; for(i=start;i<=length(text);i++) { c=substr(text,i,1); if(quoted) { if(escaped) escaped=0; else if(c=="\\") escaped=1; else if(c=="\"") quoted=0; } else if(c=="\"") quoted=1; else if(c=="{") depth++; else if(c=="}") { depth--; if(depth==0) { print substr(text,start,i-start+1); return i; } } } return 0 }
BEGIN { RS="\034" } { text=$0; at=1; needle="\"currentModel\":"; while ((p=index(substr(text,at),needle))>0) { p+=at-1+length(needle); while (substr(text,p,1) ~ /[ \t\r\n]/) p++; if(substr(text,p,1)!="{") { at=p+1; continue } end=emit_object(p); if(!end) { print "__MALFORMED__"; exit 2 } at=end+1; } }' "$decoded"
}
fetch_public_page() { slug=$1; record=$2; meta=$3; case $slug in *[!a-z0-9-]*|''|-*|*-) fail "unsafe catalog slug";; esac; url="$AA_PUBLIC_ORIGIN/models/$slug"; body=$WORK/page-$(printf '%s' "$slug" | hash_stream).html; effective=$body.url
 # Intentionally no --config, header, or credential option: this is a public page request.
 curl -q --fail --silent --show-error --proto '=https' --proto-redir '=https' --max-redirs "$PAGE_MAX_REDIRECTS" --max-time 30 --connect-timeout 5 --max-filesize "$PUBLIC_MAX_BYTES" --output "$body" --write-out '%{url_effective}' "$url" > "$effective" || fail "Artificial Analysis public page request failed"
 bytes=$(wc -c < "$body" | tr -d ' '); [ "$bytes" -le "$PUBLIC_MAX_BYTES" ] || fail "Artificial Analysis public page exceeded byte limit"; [ "$(cat "$effective")" = "$url" ] || fail "unsafe Artificial Analysis public page redirect or effective URL"
 grep -Fq "Intelligence Index v$EXPECTED_PAGE_INDEX_VERSION" "$body" || fail "unsupported public Intelligence Index methodology"
 extract_current_models "$body" > "$WORK/current-models.jsonl" || fail "malformed Artificial Analysis public page RSC"; [ "$(grep -cve '^$' "$WORK/current-models.jsonl" || :)" -eq 1 ] || fail "public page must contain exactly one currentModel record"; grep -q '__MALFORMED__' "$WORK/current-models.jsonl" && fail "malformed Artificial Analysis public page RSC"; sed -n '1p' "$WORK/current-models.jsonl" > "$record"; jq -e 'type=="object"' "$record" >/dev/null || fail "malformed Artificial Analysis public currentModel JSON"
 content=$(hash_stream < "$body"); canonical=$(jq -j -S -c . "$record" | hash_stream); retrieved=$(date +%s)000; jq -n -c --arg url "$url" --arg content "$content" --arg record "$canonical" --arg extractor "$EXTRACTOR_VERSION" --arg pageVersion "$EXPECTED_PAGE_INDEX_VERSION" --argjson retrieved "$retrieved" '{url:$url,retrievedAt:$retrieved,contentSha256:$content,recordSha256:$record,extractorVersion:$extractor,intelligenceIndexMethodologyVersion:$pageVersion}' > "$meta"
 [ "$PAGE_DELAY" = 0 ] || sleep "$PAGE_DELAY"
}
reviewed_at() { p=$1; m=$2; level=$3; now=$(date +%s)000; [ -f "$MANIFEST" ] || { printf '%s\n' "$now"; return; }; file=$(jq -r --arg p "$p" --arg m "$m" --arg l "$level" '.models[]? | select(.provider==$p and .model==$m and ((.thinkingLevel // "null") == $l)) | .file' "$MANIFEST" | head -n1); if [ -n "$file" ] && [ "$file" != null ] && [ -r "$MODELS_DIR/$file" ]; then jq -r '.mapping.reviewedAt' "$MODELS_DIR/$file"; else printf '%s\n' "$now"; fi; }
make_snapshot() { p=$1; m=$2; level=$3; aa=$4; catalog=$5; destination=$6; reviewed=$7; page=$8; page_meta=$9; captured=$(date +%s)000
 jq -e --arg aa "$aa" '[.data[]|select(.id==$aa)]|length==1' "$catalog" >/dev/null || fail "reviewed AA model id is absent or ambiguous: $aa"
 api_digest=$(jq -j -S -c --arg aa "$aa" '[.data[]|select(.id==$aa)][0]' "$catalog" | hash_stream)
 jq -S --arg p "$p" --arg m "$m" --arg level "$level" --arg aa "$aa" --arg id "$METHODOLOGY_ID" --arg version "$EXPECTED_INDEX_VERSION" --arg apiUrl "$AA_API_URL" --arg apiDigest "$api_digest" --arg pageVersion "$EXPECTED_PAGE_INDEX_VERSION" --argjson captured "$captured" --argjson reviewed "$reviewed" --slurpfile page "$page" --slurpfile pageMeta "$page_meta" '
 def num: if type=="number" and isfinite then . else null end;
 def pct: num | if . != null and . >= 0 and . <= 1 then . * 100 else . end;
 def raw($x): ($x|pct);
 def mean3($a;$b;$c): if ([$a,$b,$c]|all(type=="number")) then (($a+$b+$c)/3) else null end;
 def component($api;$public;$apiPath;$publicPath;$benchmark;$pageProvenance): if $api != null then {normalizedScore:$api,sourceKind:"api",fieldPath:$apiPath,benchmark:{id:$benchmark,version:("AA Intelligence Index v" + $version),status:"current"},retrievedAt:$captured,sourceUrl:$apiUrl,sourceRecordDigest:$apiDigest} elif $public != null then {normalizedScore:$public,sourceKind:"public-page",fieldPath:$publicPath,benchmark:{id:$benchmark,version:("AA Intelligence Index v" + $pageVersion),status:"current"},retrievedAt:$pageProvenance.retrievedAt,sourceUrl:$pageProvenance.url,sourceRecordDigest:$pageProvenance.recordSha256} else null end;
 def agree($api;$public;$field;$tolerance): if $api != null and $public != null and (($api-$public)|fabs) > $tolerance then error("API/public metric conflict: " + $field) else . end;
 def evals: (.evaluations // {});
 [.data[]|select(.id==$aa)][0] as $s | $page[0] as $r | $pageMeta[0] as $provenance | ($s|evals) as $e |
 if ($r.id != $s.id or $r.slug != $s.slug or $r.name != $s.name) then error("public currentModel identity does not exactly match catalog") else . end |
 $provenance.intelligenceIndexMethodologyVersion as $pageMethod |
 if $pageMethod != $pageVersion then error("unsupported public Intelligence Index methodology") else . end |
 ($e.artificial_analysis_intelligence_index|raw(.)) as $ai | ($r.intelligenceIndex|raw(.)) as $pi |
 ($e.artificial_analysis_agentic_index|raw(.)) as $aagent | ($r.agenticIndex|raw(.)) as $pa |
 ($e.gdpval_aa_normalized|raw(.)) as $agdp | ($r.gdpvalNormalized|raw(.)) as $pgdp |
 ($e.tau2_telecom|raw(.)) as $atau2 | ($r.tau2|raw(.)) as $ptau2 |
 ($e.tau_banking|raw(.)) as $atb | ($r.tauBanking|raw(.)) as $ptb |
 ($e.aa_lcr|raw(.)) as $alcr | ($r.lcr|raw(.)) as $plcr |
 ($e.ifbench|raw(.)) as $aif | ($r.ifbench|raw(.)) as $pif |
 ($e.hle|raw(.)) as $ahle | ($r.hle|raw(.)) as $phle |
 ($e.gpqa_diamond|raw(.)) as $agpqa | ($r.gpqa|raw(.)) as $pgpqa |
 ($e.critpt|raw(.)) as $acrit | ($r.critpt|raw(.)) as $pcrit |
 ($e.aa_omniscience_accuracy|raw(.)) as $aomni | ($r.omniscienceBreakdown.accuracy|raw(.)) as $pomni |
 ($e.aa_omniscience_non_hallucination_rate|raw(.)) as $afaith | (($r.omniscienceBreakdown.hallucinationRate|raw(.)) as $hall | if $hall==null then null else 100-$hall end) as $pfaith |
 agree($ai;$pi;"intelligenceIndex";0.51) | agree($aagent;$pa;"agenticIndex";0.51) | agree($agdp;$pgdp;"gdpvalNormalized";0.001) | agree($atau2;$ptau2;"tau2";0.001) | agree($atb;$ptb;"tauBanking";0.001) | agree($alcr;$plcr;"lcr";0.001) | agree($aif;$pif;"ifbench";0.001) | agree($ahle;$phle;"hle";0.001) | agree($agpqa;$pgpqa;"gpqa";0.001) | agree($acrit;$pcrit;"critpt";0.001) | agree($aomni;$pomni;"omniscienceBreakdown.accuracy";0.001) | agree($afaith;$pfaith;"hallucinationRate";0.001) |
 (component($atb;$ptb;"evaluations.tau_banking";"tauBanking";"tau3-banking";$provenance)) as $tau3 | (component($agdp;$pgdp;"evaluations.gdpval_aa_normalized";"gdpvalNormalized";"gdpval-aa";$provenance)) as $gdp | (component($atau2;$ptau2;"evaluations.tau2_telecom";"tau2";"tau2-telecom";$provenance)) as $tau2 |
 (if $tau3 != null and $gdp != null then {version:"v1",rule:"tau3-banking+gdpval-aa",score:(($tau3.normalizedScore+$gdp.normalizedScore)/2)} elif $tau2 != null then {version:"v1",rule:"tau2-telecom-fallback",score:$tau2.normalizedScore} else {version:"v1",rule:"unavailable",score:null} end) as $toolDerivation |
 {version:4,provider:$p,model:$m,thinkingLevel:(if $level=="null" then null else $level end),modelId:$aa,capturedAt:$captured,methodology:{id:$id,version:$version},mapping:{status:"mapped",matchBasis:"manual",reviewedAt:$reviewed,thinkingLevel:(if $level=="null" then null else $level end)},source:{name:$s.name,slug:$s.slug,openrouterApiId:($s.openrouter_api_id // null)},publicPage:$provenance,scores:{intelligence:($ai // $pi),coding:($e.artificial_analysis_coding_index|raw(.)),agentic:($aagent // $pa),toolUse:$toolDerivation.score,scientificReasoning:mean3(($ahle // $phle);($agpqa // $pgpqa);($acrit // $pcrit)),longContext:($alcr // $plcr),instructionFollowing:($aif // $pif),knowledge:($aomni // $pomni),faithfulness:($afaith // $pfaith)},toolUse:{components:{tau3Banking:$tau3,gdpvalAaNormalized:$gdp,tau2Telecom:$tau2},derivation:$toolDerivation},outputTokens:{},taskTimeMs:{},coverage:0} |
 .coverage=([.scores[]|select(.!=null)]|length)/(.scores|length) |
 if (.source.name|type)!="string" or (.source.slug|type)!="string" then error("missing AA identity fields") else . end |
 if ([.scores[]|select(.!=null and ((type!="number") or .<0 or .>100))]|length)!=0 then error("AA evaluation value is outside the routing scale") else . end' "$catalog" > "$destination" || fail "Artificial Analysis response cannot be mapped to the reviewed benchmark schema"; }
process_mapping() { p=$1; m=$2; level=$3; aa=$4; catalog=$5; entries=$6; staged=$7; reviewed=$(reviewed_at "$p" "$m" "$level"); slug=$(jq -er --arg aa "$aa" '[.data[]|select(.id==$aa)][0].slug | select(type=="string")' "$catalog") || fail "reviewed AA model has no safe catalog slug"; page=$WORK/page-record-$(printf '%s' "$aa"|hash_stream).json; page_meta=$WORK/page-meta-$(printf '%s' "$aa"|hash_stream).json; fetch_public_page "$slug" "$page" "$page_meta"; candidate=$WORK/candidate-$(printf '%s/%s/%s' "$p" "$m" "$level" | hash_stream).json; make_snapshot "$p" "$m" "$level" "$aa" "$catalog" "$candidate" "$reviewed" "$page" "$page_meta"; ih=$(printf '%s/%s/%s' "$p" "$m" "$level"|hash_stream); sh=$(jq -j -S -c 'del(.capturedAt)' "$candidate"|hash_stream); file=$(printf '%.16s-%.16s.json' "$ih" "$sh"); chmod 600 "$candidate"; mv "$candidate" "$staged/$file"; content=$(jq -j -S -c . "$staged/$file"|hash_stream); jq -n -c --arg p "$p" --arg m "$m" --arg l "$level" --arg aa "$aa" --arg file "$file" --arg content "$content" --argjson captured "$(jq .capturedAt "$staged/$file")" '{provider:$p,model:$m,thinkingLevel:(if $l=="null" then null else $l end),modelId:$aa,file:$file,capturedAt:$captured,contentDigest:$content}' >> "$entries"; }
publish_entries() { entries=$1; staged=$2; now=$(date +%s)000; models=$WORK/models-array.json; jq -s 'sort_by(.provider,.model,(.thinkingLevel // ""))' "$entries" > "$models"; jq -e '[group_by([.provider,.model,.thinkingLevel])[]|select(length>1)]|length==0 and ([group_by([.provider,.model,.modelId])[]|select(length>1)]|length==0) and ([group_by([.provider,.model])[]|select(length>1 and any(.[];.thinkingLevel==null))]|length==0)' "$models" >/dev/null || fail "duplicate or mixed generic/variant Pi model mapping"; digest=$(jq -j -S -c . "$models"|hash_stream); next=$WORK/manifest.json; jq -n -S --arg id "$METHODOLOGY_ID" --arg version "$EXPECTED_INDEX_VERSION" --arg digest "$digest" --argjson generated "$now" --slurpfile models "$models" '{version:4,generatedAt:$generated,digest:$digest,methodology:{id:$id,version:$version},models:$models[0]}' > "$next"; mkdir -p "$ROOT" "$MODELS_DIR"; chmod 700 "$ROOT" "$MODELS_DIR"; for file in "$staged"/*.json; do [ -e "$file" ] || break; mv "$file" "$MODELS_DIR/"; done; chmod 600 "$next"; mv "$next" "$MANIFEST"; for old in "$MODELS_DIR"/*.json; do [ -e "$old" ] || break; file=${old##*/}; jq -e --arg file "$file" '.models[] | select(.file == $file)' "$MANIFEST" >/dev/null || rm -f -- "$old"; done; }
# v3 is accepted only here as a mapping-only input for an atomic v4 refresh. Scores and provenance are never carried forward.
extract_v3_mappings() { manifest=$1; jq -e '. as $root | $root.version == 3 and ($root.models|type == "array") and ([$root.models[] | select((keys|sort) == ["aaModelId","capturedAt","contentDigest","file","model","provider","thinkingLevel"] and (.provider|type=="string" and length>0) and (.model|type=="string" and length>0) and (.aaModelId|type=="string" and length>0) and (.thinkingLevel == null or .thinkingLevel == "off" or .thinkingLevel == "low" or .thinkingLevel == "medium" or .thinkingLevel == "high" or .thinkingLevel == "xhigh" or .thinkingLevel == "max"))] | length == ($root.models|length))' "$manifest" >/dev/null || fail "v3 migration requires a strict v3 manifest"; jq '[.models[]|{provider,model,thinkingLevel,aaModelId}]' "$manifest"; }
validate_mappings() { file=$1; jq -e '. as $items | type=="array" and ([.[]|select(type=="object" and (keys|sort)==["aaModelId","model","provider","thinkingLevel"] and (.provider|type=="string" and length>0) and (.model|type=="string" and length>0) and (.aaModelId|type=="string" and length>0) and (.thinkingLevel==null or .thinkingLevel=="off" or .thinkingLevel=="low" or .thinkingLevel=="medium" or .thinkingLevel=="high" or .thinkingLevel=="xhigh" or .thinkingLevel=="max"))]|length == ($items|length)) and ([group_by([.provider,.model,.thinkingLevel])[]|select(length>1)]|length==0) and ([group_by([.provider,.model,.aaModelId])[]|select(length>1)]|length==0) and ([group_by([.provider,.model])[]|select(length>1 and any(.[];.thinkingLevel==null))]|length==0)' "$file" >/dev/null || fail "invalid, duplicate, or mixed generic/variant batch mapping"; jq -r '.[]|[.provider,.model,(.thinkingLevel // "null")]|@tsv' "$file" | while IFS="$(printf '\t')" read -r p m level; do configured_models | grep -Fx "$p/$m" >/dev/null || fail "model is not enabled: $p/$m"; controllable=$(jq -r --arg p "$p" '.providers[$p].compat.supportsReasoningEffort | if type == "boolean" then tostring else empty end' "$MODELS"); [ "$controllable" != false ] || [ "$level" = null ] || fail "provider does not support selectable reasoning effort: $p/$m"; done; }
refresh_mappings() { mappings=$1; setup_curl_config; catalog=$WORK/catalog.json; fetch_catalog "$catalog"; jq -r '.[].aaModelId' "$mappings" | while IFS= read -r aa; do jq -e --arg aa "$aa" '[.data[]|select(.id==$aa)]|length==1' "$catalog" >/dev/null || fail "reviewed AA model id is absent or ambiguous: $aa"; done; entries=$WORK/entries.jsonl; : > "$entries"; [ ! -f "$WORK/preserve.jsonl" ] || cat "$WORK/preserve.jsonl" >> "$entries"; staged=$WORK/models; mkdir -p "$staged"; jq -r '.[]|[.provider,.model,(.thinkingLevel // "null"),.aaModelId]|@tsv' "$mappings" | while IFS="$(printf '\t')" read -r p m level aa; do process_mapping "$p" "$m" "$level" "$aa" "$catalog" "$entries" "$staged"; done; publish_entries "$entries" "$staged"; }
[ $# -gt 0 ] || { usage; exit 2; }
case "$1" in
 --missing) [ $# -eq 1 ] || { usage; exit 2; }; missing ;;
 --check) [ $# -eq 1 ] || { usage; exit 2; }; check_snapshot; echo "Artificial Analysis snapshot is valid" ;;
 --discover) [ $# -eq 2 ] || { usage; exit 2; }; configured_models|grep -Fx "$2" >/dev/null || fail "model is not enabled: $2"; setup_curl_config; catalog=$WORK/catalog.json; fetch_catalog "$catalog"; q=${2#*/}; jq -r --arg q "$q" '[.data[]|select((.openrouter_api_id?==$q) or (.slug?==$q) or ((.name? // "")|ascii_downcase|contains($q|ascii_downcase)))][]|[.id,.slug,.name]|@tsv' "$catalog" ;;
 --add) target=${2-}; aa=${4-}; level=null; [ $# -ge 4 ] && [ "$3" = "--aa-model-id" ] || { usage; exit 2; }; if [ $# -eq 6 ] && [ "$5" = "--thinking-level" ]; then level=$6; elif [ $# -ne 4 ]; then usage; exit 2; fi; valid_level "$level" || fail "invalid thinking level"; configured_models|grep -Fx "$target" >/dev/null || fail "model is not enabled: $target"; p=${target%%/*}; m=${target#*/}; tmp=$WORK/add.json; jq -n --arg p "$p" --arg m "$m" --arg l "$level" --arg aa "$aa" '[{provider:$p,model:$m,thinkingLevel:(if $l=="null" then null else $l end),aaModelId:$aa}]' > "$tmp"; if [ -f "$MANIFEST" ]; then jq --arg p "$p" --arg m "$m" --arg l "$level" '[.models[]|select(.provider!=$p or .model!=$m or ((.thinkingLevel // "null") != $l))|{provider,model,thinkingLevel:(.thinkingLevel // null),aaModelId:.modelId}]' "$MANIFEST" > "$tmp".old; jq -s '.[0]+.[1]' "$tmp" "$tmp".old > "$tmp".next; mv "$tmp".next "$tmp"; fi; validate_mappings "$tmp"; refresh_mappings "$tmp" ;;
 --replace-batch) [ $# -eq 2 ] && [ -r "$2" ] || { usage; exit 2; }; validate_mappings "$2"; refresh_mappings "$2" ;;
 --refresh) [ $# -eq 2 ] || { usage; exit 2; }; [ -f "$MANIFEST" ] || fail "no existing mapping for $2"; p=${2%%/*}; m=${2#*/}; tmp=$WORK/refresh.json; jq -e --arg p "$p" --arg m "$m" '[.models[]|select(.provider==$p and .model==$m)|{provider,model,thinkingLevel,aaModelId:.modelId}]|length>0' "$MANIFEST" >/dev/null || fail "no existing mapping for $2"; jq -c --arg p "$p" --arg m "$m" '[.models[]|select(.provider==$p and .model==$m)|{provider,model,thinkingLevel,aaModelId:.modelId}]' "$MANIFEST" > "$tmp"; jq -c --arg p "$p" --arg m "$m" '.models[]|select(.provider!=$p or .model!=$m)' "$MANIFEST" > "$WORK/preserve.jsonl"; refresh_mappings "$tmp" ;;
 --refresh-all) [ $# -eq 1 ] || { usage; exit 2; }; [ -f "$MANIFEST" ] || fail "no benchmark manifest"; version=$(jq -r '.version // empty' "$MANIFEST"); case $version in 4) jq -e '.models|type == "array"' "$MANIFEST" >/dev/null || fail "invalid v4 manifest"; jq '[.models[]|{provider,model,thinkingLevel,aaModelId:.modelId}]' "$MANIFEST" > "$WORK/all.json" ;; 3) extract_v3_mappings "$MANIFEST" > "$WORK/all.json" ;; *) fail "unsupported manifest version" ;; esac; validate_mappings "$WORK/all.json"; refresh_mappings "$WORK/all.json" ;;
 *) usage; exit 2 ;;
esac
