{
	"data": "ENC[AES256_GCM,data:VPpKmuMZpnRDxFnbNuQ8OPUFZptxSRG6zFtwTJ8jFA2QRkjOjsrSYBp42aao04tvJzsnVOs=,iv:LfInsivQyY1opbMo/NQRIBAOpvLYR8jf+hgZSXoDfoc=,tag:cjwoYyHUvTFUaQX79/MrSA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNjFTc3QrZW1RVUhobzlF\nWng3VTAzZ1JJV2JsTUhJRk1ERVBjaVBObDJrCmNVdndKNDlnYTEzbEUzWHE3VDNJ\nVi9EMThuZytPRkZoZndtRFhtWWxzSTQKLS0tIHMxSnUzT1c2OWlPeXRWa0dVdHgx\nUm9SYk5naGJFRGEyRWtkMGZheTl6YU0K48isPAsu5xtWiEpEYmJPiZp+D+pTGd3M\nXagnbmt+CjolR1aNq10EZ/prHlIVLsJ0YDB59PSUVJ3XFZ7XcUqgrA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1ykg448l6aj2znrqc4y00uzjfzkx7v7gdpj7xjymnjsg7vh4mjd7sj4mney"
			}
		],
		"lastmodified": "2026-06-25T19:25:40Z",
		"mac": "ENC[AES256_GCM,data:YLm2wKmU9Dy7VQxUaDJ24+3yy0+RVva0MWl7gtx54iBVO4XQo+55GlZQwBClQvKJdsojR0s750v2YQgiwzOPD0KfjANalFGgSzKVa7O+HFHR6aNw9pz2+24BqsJM7CwDSPmDyiMIruLJ6FhulBrevy/9LZyZYQGkgItF6V0A2B0=,iv:sEX138OWGFzk5mJyR1lZbX9c1Z1Uu+5VT8TDj3KYgtM=,tag:Uwd+W3gF8FwX39hhmYejHQ==,type:str]",
		"version": "3.13.1"
	}
}
