{
	"data": "ENC[AES256_GCM,data:v4Q8L75v+cXoECA4j70Yqrdvd598FgSuGG6TT06493iGsOQWPt2pRr7MBRh48bDiHfE/kAQ=,iv:AeqDNwQdMVq9BSxWmChw5395/MPH8ykG1keb9AZO6UM=,tag:6PDzPU3dhCUa+dfzBs+5Lw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZnA4QjQrZFhMMSs4Rkl0\nSldMMERIMDcySHZJQmZNNnNMN09tYllqcVhJCmhXMmtPeWMzZ0h0UlBUQXVFVHh5\nU3RxZUlzNlpXQ25kUUtqYWZDbjZyZWsKLS0tIDM1c0RVTjg5MkQxa2xXVERHSG9W\nekRyVkdna2EwM2VrK3ZnOHNqTElNdTgKJltLugPh6TLZosU7V+cpDwz3oTjQ+OzP\nb3Gmz/RAEqGZ/ces3hRfkf4qHJ86k9Gr2b8MqD/CaCH0k4dhQsjLkA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1ykg448l6aj2znrqc4y00uzjfzkx7v7gdpj7xjymnjsg7vh4mjd7sj4mney"
			}
		],
		"lastmodified": "2026-06-20T03:17:37Z",
		"mac": "ENC[AES256_GCM,data:5xi/oDgvLF1fPW7yjbhGtDH+CKik24ylYkSoabGrzOhriryMzf4hcl+te95St7js/E+gvxk+b/GGHFBB95XZpwf2SA/z9eo8krQ7KvuDj0vw7lyx576QLjiRCSrOFWa9NAnnQIKw/i0RH7OO2FLeGZWRmS6hqWEKG8/PJBvpOBA=,iv:BuPHQiY3KvnRQXl8tDrrbKn1Cttr381xsQv9AUfDjPQ=,tag:BirZV9nDGvOilNU4u4oE5g==,type:str]",
		"version": "3.13.1"
	}
}
