{
	"data": "ENC[AES256_GCM,data:YdBBpxJrfDmfhR66jJVO6gocllKVslAgaaOCWAfbeN31+3cmE++IV5/uE6fe2G2umQFf0UQ=,iv:PTWur9uZPSKalRUN4YttZd3Ew/ZxiofpijfWECndfio=,tag:8AiipvYEY69IoK3NXPRYdw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVkt5VVVYT2tVMmNKb1FO\nSEtVVnE2anRWUUQvdjEyeVdSZTRmeTFMdFRRCno1bVhnQk51Um1NV2tEOGZJSGdK\nc2IvaUw4VmdVdUQzbVpoRzNaV3R1UTAKLS0tIGtjNjlGeHNEQjBYczNEc2FrZW9I\najRDS1hNQnVkT2pwWGJ5ZEV4TTVQdmMK1IO8sthy5BOCqMeKCNo9qP6fOgek8SNT\ntnqzgXBff/FzdWpjdlRuA1dqoklQAQr/Asr8r6IEYr9sroFRNEXHQQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1ykg448l6aj2znrqc4y00uzjfzkx7v7gdpj7xjymnjsg7vh4mjd7sj4mney"
			}
		],
		"lastmodified": "2026-07-09T13:23:33Z",
		"mac": "ENC[AES256_GCM,data:V3HVk7N4nHrbKquqOrB7ZEWZVDqtPAWBSIVYafQ8MBA9rxtvv0Zz65XSVY1r+HmeIBZgr0wnc6emuUpHXW8HmEitY9BZC+vUwB2PgKzF2k9MX8oCBKmKk+z/SPMiMH1Ty89p0j6eEgv5qIjCOZF9Z6YcCi2whTt4SKlXKdlL2Vg=,iv:PAMbsfQsTmLBGhNpQkAUmaRhiLPVKm4jouRlXmXkMYo=,tag:MKuJc0xV53QizJuTa+5w1g==,type:str]",
		"version": "3.13.1"
	}
}
