{
	"data": "ENC[AES256_GCM,data:8STSt4n+GrqNzALxKKQrlND/OsmORxSDxw==,iv:jCtot6iJ/Qj0nHmUbmlLrybkNoxFpU82qaxM+7DAZjU=,tag:u1q/XQVYyZ83Lz9uBsi5BA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1ykg448l6aj2znrqc4y00uzjfzkx7v7gdpj7xjymnjsg7vh4mjd7sj4mney",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aW9QNnkyYktsNk9NaUhs\nQzl1eW5NdWs4VUJVbTZGY0NoUWo3TDRrMnpVCmhYdWhrMVFaTXA2VmE0U0Z2TWht\nY1lXRzY2UHZJUUMzcTFkTlo1dG5VV00KLS0tIGUyUjlpcHdEdTFBVTI3MGRLSlNT\nN1FMRElnQWZFWFVSdnJGRGhXS3ZMSDQKjjPi4Uaso16rNgvkG6DPzf+XWg7X88Hm\ny5Neg60ueeuuZbvjGN0vr5psvWt1P7lP3JRz26VG784dSYFUpczv6Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-27T15:00:34Z",
		"mac": "ENC[AES256_GCM,data:XORevxniON2JLLfXWgKTAc9QZoSRc+kC/AZt8mmdHG9Sqgn9jt8SuwXIReSZ3HaoEQQntt9ysRZmbRhYAtGP/SyOlrqFz6zsdgh4In+JxrpdJ331b9Erar23Jr6rXK0mFjqc83lY+tw0RNaOw+gZv0OVDdPUK82LFyxPDoywqfE=,iv:nOyId1TlIytFXIs/PLPGKCniw4xbadbWDnajhuu2k+Q=,tag:qY2bWZDr58qTgGUpSYsDMA==,type:str]",
		"version": "3.12.2"
	}
}
